spring.datasource.url=jdbc:mysql://localhost:3306/aula_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=*****
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


security.config.prefix=Bearer 
security.config.key=minha_chave_super_secreta
security.config.expiration=3600000
